set(PACKAGE_PLUGIN_DIR "${CMAKE_CURRENT_SOURCE_DIR}/dist/Data/F4SE/Plugins/FO4GraphicsOverhaul")

add_custom_command(TARGET FO4GraphicsOverhaul POST_BUILD
    COMMAND "${CMAKE_COMMAND}" -E make_directory "${PACKAGE_PLUGIN_DIR}/LICENSES"
    COMMAND "${CMAKE_COMMAND}" -E copy_if_different "${CMAKE_CURRENT_SOURCE_DIR}/LICENSE" "${PACKAGE_PLUGIN_DIR}/LICENSES/LICENSE"
    COMMAND "${CMAKE_COMMAND}" -E copy_if_different "${CMAKE_CURRENT_SOURCE_DIR}/EXCEPTIONS.md" "${PACKAGE_PLUGIN_DIR}/LICENSES/EXCEPTIONS.md"
    COMMAND "${CMAKE_COMMAND}" -E copy_if_different "${CMAKE_CURRENT_SOURCE_DIR}/THIRD-PARTY-NOTICES.md" "${PACKAGE_PLUGIN_DIR}/LICENSES/THIRD-PARTY-NOTICES.md"
    COMMAND "${CMAKE_COMMAND}" -E copy_directory "${CMAKE_CURRENT_SOURCE_DIR}/LICENSES" "${PACKAGE_PLUGIN_DIR}/LICENSES"
    COMMENT "packaging licence texts into dist/"
    VERBATIM
)
